# Generated by Django 4.0.5 on 2022-06-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10, verbose_name='Тег')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('full_text', models.TextField(verbose_name='Текст статьи')),
            ],
        ),
    ]
