# Generated by Django 3.1.7 on 2022-12-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20221223_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('tagId', models.AutoField(db_column='tagId', primary_key=True, serialize=False)),
                ('tagName', models.TextField(db_column='tagName', unique=True)),
            ],
            options={
                'db_table': 'texts_tags',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='articles',
            name='tag',
            field=models.CharField(default=1, max_length=10, verbose_name='Тег'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
